parameters:
#    acme_test.example.class: Acme\TestBundle\Example

services:
#    acme_test.example:
#        class: %acme_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    # acme.test.admin.product:
    #     class: Acme\TestBundle\Admin\ProductAdmin
    #     tags:
    #         - { name: sonata.admin, manager_type: orm, group: Tables, label: Products }
    #     arguments: [ null, Acme\TestBundle\Entity\Product, AcmeTestBundle:ProductAdmin ]

    # acme.test.admin.category:
    #     class: Acme\TestBundle\Admin\CategoryAdmin
    #     tags:
    #         - { name: sonata.admin, manager_type: orm, group: Tables, label: Categories }
    #     arguments: [ null, Acme\TestBundle\Entity\Category, AcmeTestBundle:CategoryAdmin ]